### ISSUE TITLE
Identity contract: Manage supported networks

### ISSUE THREAD

**Issue by cuteolaf** [TheDotflow/dotflow-ink#7]
We are storing the networks in a vector of tuples  - `network` and `address`.
```rust
addresses: Vec<(Network, Address)>
```
Here, `network` is of type `String` and has no length limit.
This is not a good practice in terms of storage management.
Another downside of this approach is that Users might use different strings for the same network.
e.g. "Polkadot", "polkadot", "polkadoT" for Polkadot network

A solution I would like to suggest is:
- Add a new storage item for supported networks
   ```rust
   supported_networks: Vec<Network>
   ```
- The contract creator will be able to add or remove supported networks.
   ```rust
   add_network(network: String)
   remove_network(id: u32)
   update_network(id: u32, new_name: String)
   ```
   With these items and methods being added, we just need to store the `id` of the network

**Comment by Szegoo** [comment]
> Another downside of this approach is that Users might use different strings for the same network.
e.g. "Polkadot", "polkadot", "polkadoT" for Polkadot network

Users should be using the UI so these kinds of errors shouldn't really happen.

The reason I think this would be a good idea is because it is more practical to store the supported networks in the contract than having it hardcoded on the frontend.
